version: '3'

services:
  web:
    build: .
    command: gunicorn blog_api.wsgi:application -b 0.0.0.0:8000
    expose:
      - "8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    networks:
      - djangonetwork

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - djangonetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:


networks:
  djangonetwork:
    driver: bridge