services:
  - name: web
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
    buildCommand: "gunicorn blog_api.wsgi:application -b 0.0.0.0:8000"
    startCommand: "gunicorn blog_api.wsgi:application -b 0.0.0.0:$PORT"
    secrets:
      - name: DATABASE_URL

  - name: db
    envVars:
      - key: POSTGRES_DB
        fromSecret: DATABASE_URL
      - key: POSTGRES_USER
        fromSecret: DATABASE_URL
      - key: POSTGRES_PASSWORD
        fromSecret: DATABASE_URL
    image: "postgres:latest"
    ports:
      - 5432:5432

  - name: nginx
    image: "nginx:latest"
    startCommand: "nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"
    dependsOn:
      - web
    volumes:
      - name: static_volume
        path: "/app/static"
      - name: media_volume
        path: "/app/media"
      - name: nginx_conf
        path: "/etc/nginx/nginx.conf"
    ports:
      - 80:80

secrets:
  - name: SECRET_KEY
    value: "your_secret_key"
  - name: DATABASE_URL
    value: "postgres://dev:dev@db:5432/dev"

volumes:
  - name: static_volume
  - name: media_volume
  - name: nginx_conf
    mountPath: "/etc/nginx/nginx.conf"